
package com.example.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InfoServiceImplService", targetNamespace = "http://service.example.com/", wsdlLocation = "http://localhost:8080/services/InfoService?wsdl")
public class InfoServiceImplService
    extends Service
{

    private final static URL INFOSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException INFOSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName INFOSERVICEIMPLSERVICE_QNAME = new QName("http://service.example.com/", "InfoServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/services/InfoService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INFOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        INFOSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public InfoServiceImplService() {
        super(__getWsdlLocation(), INFOSERVICEIMPLSERVICE_QNAME);
    }

    public InfoServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INFOSERVICEIMPLSERVICE_QNAME, features);
    }

    public InfoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, INFOSERVICEIMPLSERVICE_QNAME);
    }

    public InfoServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INFOSERVICEIMPLSERVICE_QNAME, features);
    }

    public InfoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InfoService
     */
    @WebEndpoint(name = "InfoServiceImplPort")
    public InfoService getInfoServiceImplPort() {
        return super.getPort(new QName("http://service.example.com/", "InfoServiceImplPort"), InfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoService
     */
    @WebEndpoint(name = "InfoServiceImplPort")
    public InfoService getInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.example.com/", "InfoServiceImplPort"), InfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INFOSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw INFOSERVICEIMPLSERVICE_EXCEPTION;
        }
        return INFOSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
