
package com.example.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InfoService", targetNamespace = "http://service.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InfoService {


    /**
     * 
     * @param name
     * @return
     *     returns com.example.service.Greeting
     */
    @WebMethod
    @WebResult(name = "Greeting", targetNamespace = "")
    @RequestWrapper(localName = "sayHowAreYou", targetNamespace = "http://service.example.com/", className = "com.example.service.SayHowAreYou")
    @ResponseWrapper(localName = "sayHowAreYouResponse", targetNamespace = "http://service.example.com/", className = "com.example.service.SayHowAreYouResponse")
    public Greeting sayHowAreYou(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
